#!/usr/bin/env python3
"""build-sources.py — regenerate each page's Sources block from canonical data/sources/.

CANONICAL SOURCE: data/sources/<path-mirroring-guides>.json. This rewrites the
`<section class="credits" id="section-credits">` block of each page from its data file —
the data is the source of truth, the credits HTML is generated. Don't hand-edit the block.

The existing `sec-num` (positional) and the section's leading indent are read from the page
and preserved; the build owns the rest of the block's formatting. Idempotent.

Also (re)writes data/sources/_index.md — a generated catalog of every unique external URL
and the pages that cite it (the "all sources in one place" view).

Usage:
    python3 scripts/build-sources.py                       # build all
    python3 scripts/build-sources.py systems/superpower    # matching path fragments
    python3 scripts/build-sources.py --check               # report diffs, write nothing
    python3 scripts/build-sources.py --no-index            # skip rewriting _index.md
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import sources_lib as L  # noqa: E402

INDEX_MARKER = "<!-- generated by scripts/build-sources.py -->"


def load_data_files(filters):
    files = sorted(L.DATA_DIR.rglob("*.json"))
    if filters:
        files = [f for f in files
                 if any(frag in str(f).replace("\\", "/") for frag in filters)]
    return files


def build_index(data_files):
    """unique URL -> list of citing page-rel paths."""
    urls = {}
    for df in data_files:
        data = json.loads(df.read_text(encoding="utf-8"))
        for s in data["sources"]:
            urls.setdefault(s["url"], {"label": s["label"], "pages": set()})
            urls[s["url"]]["pages"].add(data["page"])
    lines = [
        "# Sources index",
        "",
        INDEX_MARKER,
        "",
        "Every unique external reference cited across the site's **Sources** sections, with the",
        "pages that cite it. Canonical data lives in `data/sources/**.json`; regenerate this",
        "file with `python3 scripts/build-sources.py`.",
        "",
        f"**{len(urls)} unique URLs** across **{len(data_files)} pages**.",
        "",
        "| Source | URL | Cited by |",
        "|---|---|---|",
    ]
    for url in sorted(urls):
        entry = urls[url]
        pages = ", ".join(sorted(p.replace("guides/", "") for p in entry["pages"]))
        label = entry["label"].replace("|", "\\|")
        lines.append(f"| {label} | <{url}> | {pages} |")
    return "\n".join(lines) + "\n"


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    check = "--check" in sys.argv
    no_index = "--no-index" in sys.argv

    data_files = load_data_files(args)
    if not data_files:
        print("no matching data files.")
        return

    changed = 0
    for df in data_files:
        data = json.loads(df.read_text(encoding="utf-8"))
        page = L.ROOT / data["page"]
        if not page.exists():
            print(f"  MISSING PAGE: {data['page']} (from {df.name})")
            continue
        text = L.read_text(page)
        parsed = L.parse_credits(text)
        if parsed is None:
            print(f"  NO CREDITS SECTION: {data['page']}")
            continue
        rows = data["sources"]
        block = L.render_credits(parsed["indent"], parsed["sec_num"], data["lead"],
                                 rows, L.detect_eol(text), tag=data.get("tag"))
        new_text = L.replace_credits(text, parsed, block)
        if new_text != text:
            changed += 1
            rel = data["page"]
            if check:
                print(f"  would update {rel}")
            else:
                L.write_text(page, new_text)
                print(f"  updated {rel}")

    if not no_index:
        index_md = build_index(data_files) if not args else \
            build_index(sorted(L.DATA_DIR.rglob("*.json")))
        index_path = L.DATA_DIR / "_index.md"
        if check:
            print(f"  would write {index_path.relative_to(L.ROOT)}")
        else:
            index_path.write_text(index_md, encoding="utf-8")
            print(f"  wrote {index_path.relative_to(L.ROOT)}")

    print()
    print(f"data files: {len(data_files)}   pages changed: {changed}")
    if check:
        print("--check: nothing written.")


if __name__ == "__main__":
    main()
