#!/usr/bin/env bash
#
# generate-anchor-files.sh
# -----------------------------------------------------------------------------
# Regenerates the per-page anchor reference files — one sibling
# `<basename>-anchors.md` next to every guide HTML, cataloging that page's
# `<section id="...">` navigation anchors with human-readable labels.
#
# WHAT IT DOES
#   - For each guides/**/*.html, extracts every `<section id="…">` and the text
#     of that section's first heading (the section title), and writes a sibling
#     `<basename>-anchors.md` listing `- **Title** — `#id`` in document order.
#   - Pages with NO section anchors (e.g. the farm pages) get no file; a stale
#     generated file for such a page is removed so the tree stays in sync.
#   - HTML entities in titles are decoded (&amp; &mdash; &quot; …).
#
# WHAT IT DOESN'T TOUCH
#   - The hand-curated catalogs listed in CURATED below (blueprints / engineers)
#     carry richer, manually-maintained annotations (`#grp-`, `#bp-`, `#eng-`
#     ids + notes) that can't be derived mechanically. They are never written.
#   - Only files containing the generated marker are ever overwritten/removed, so
#     hand-authored anchor files are always safe.
#
# WHEN TO RE-RUN
#   - After adding, removing, or renaming any guide HTML.
#   - After adding/removing/renaming any `<section id="…">` in a guide.
#
# USAGE
#   bash scripts/generate-anchor-files.sh        # from anywhere in the repo
#
# OUTPUT
#   guides/**/<basename>-anchors.md  (overwritten)
#   Prints generated / skipped counts as a sanity check.
# -----------------------------------------------------------------------------
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
GUIDES="$REPO_ROOT/guides"

# Marker line written into every generated file — used to tell our own output
# apart from hand-curated anchor files before overwriting or deleting.
MARKER='> Generated by `scripts/generate-anchor-files.sh` — do not edit by hand.'

# Pages whose anchor catalog is hand-maintained (richer than this script emits).
# Paths are relative to guides/.
CURATED=(
  "engineering/engineering-manuals/blueprints.html"
  "engineering/engineering-manuals/engineers.html"
)

is_curated() {
  local rel="$1" c
  for c in "${CURATED[@]}"; do [[ "$rel" == "$c" ]] && return 0; done
  return 1
}

# Is $1 a file we generated (safe to overwrite/remove)?
is_generated_file() {
  [[ -f "$1" ]] && grep -qF "$MARKER" "$1"
}

# Emit the section bullets for one HTML file (one `- **Title** — `#id`` per line).
extract_anchors() {
  awk '
    # Section open tag — capture its id and start looking for the first heading.
    /<section[^>]*id="[^"]+"/ {
      match($0, /id="[^"]+"/); id = substr($0, RSTART + 4, RLENGTH - 5)
      pend = 1; next
    }
    pend == 1 {
      line = $0
      if (match(line, /<h[1-6][^>]*>/)) {
        rest = substr(line, RSTART + RLENGTH)            # text after the opening <hN>
        if (match(rest, /<\/h[1-6]>/)) rest = substr(rest, 1, RSTART - 1)
        gsub(/<[^>]*>/, "", rest)                        # strip inline tags (em / span)
        gsub(/&mdash;/, "\xe2\x80\x94", rest)            # — em dash
        gsub(/&ndash;/, "\xe2\x80\x93", rest)            # – en dash
        gsub(/&#39;/,  "\x27", rest)
        gsub(/&quot;/, "\"",  rest)
        gsub(/&nbsp;/, " ",   rest)
        gsub(/&amp;/,  "\\&", rest)                      # decode &amp; LAST
        gsub(/^[ \t]+|[ \t]+$/, "", rest)                # trim
        gsub(/[ \t]+/, " ", rest)                        # collapse inner whitespace
        printf "- **%s** \xe2\x80\x94 `#%s`\n", rest, id
        pend = 0
      }
    }
  ' "$1"
}

generated=0; curated=0; empty=0; total=0

while IFS= read -r html; do
  rel="${html#"$GUIDES"/}"
  base="$(basename "$html" .html)"
  out="$(dirname "$html")/${base}-anchors.md"

  if is_curated "$rel"; then
    curated=$((curated + 1))
    continue
  fi

  body="$(extract_anchors "$html")"
  n=0
  [[ -n "$body" ]] && n="$(printf '%s\n' "$body" | grep -c '^- ' || true)"

  if [[ "$n" -eq 0 ]]; then
    # No navigation anchors — drop a stale generated file if we own it.
    if is_generated_file "$out"; then rm -f "$out"; fi
    empty=$((empty + 1))
    continue
  fi

  {
    printf '# %s.html — Anchor Reference\n\n' "$base"
    printf 'Link format: `%s.html#<id>`\n\n' "$base"
    printf '%s\n\n' "$MARKER"
    printf '## Sections\n'
    printf '%s\n' "$body"
  } > "$out"

  generated=$((generated + 1))
  total=$((total + n))
done < <(find "$GUIDES" -name '*.html' | sort)

echo "anchor files generated : $generated  ($total anchors total)"
echo "hand-curated, skipped   : $curated  (${CURATED[*]})"
echo "no section anchors      : $empty"
